name: tf-plan-and-lint

on:
  pull_request:
    paths:
      - "feature-store/infra/**.tf"
      - ".pre-commit-config.yaml"
      - ".github/workflows/**"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsFlashfeat
          aws-region: ap-south-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8

      - name: Install TFLint
        run: |
          curl -sSL https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh \
            | bash -s -- v0.50.3
          sudo mv ./tflint /usr/local/bin/

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Init backend
        run: terraform -chdir=feature-store/infra init \
          -backend-config=backend.dev.tfbackend

      - name: Terraform plan
        run: terraform -chdir=feature-store/infra plan
