name: tf-plan-and-lint

on:
  pull_request:
    paths:
      - "feature-store/infra/**.tf"
      - "feature-store/app/**.go"
      - ".github/workflows/**"

permissions:
  id-token: write
  contents: read

jobs:
  build-go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: feature-store/app
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Cache Go
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ${{ github.workspace }}/feature-store/app/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('feature-store/app/go.sum') }}

      - name: Run unit tests
        run: go test ./...

      - name: Build CLI binaries
        run: |
          CGO_ENABLED=0 go build -tags netgo -o sidecar ./cmd/sidecar
          CGO_ENABLED=0 go build -tags netgo -buildmode=pie -o enclave ./cmd/enclave
          CGO_ENABLED=0 go build -tags netgo -o seed   ./cmd/seed
          CGO_ENABLED=0 go build -tags netgo -o model  ./cmd/model

      - uses: actions/upload-artifact@v4
        with:
          name: flashfeat-binaries
          path: |
            feature-store/app/sidecar
            feature-store/app/enclave
            feature-store/app/seed
            feature-store/app/model

  terraform:
    needs: build-go
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: feature-store/infra

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsFlashfeat
          aws-region: ap-south-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8

      - name: Init backend
        run: terraform init

      - name: Terraform plan
        run: terraform plan
